import Head from "next/head";
import Script from "next/script";

export default function HeadComponent({pageName}){
  return(
    <>
      <Head key={pageName}>
        <title>{pageName}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    </>
  )
}
