import Navigation from '../ui/Navigation/index.jsx';
import SiteMap from '../ui/SiteMap/index.jsx';
import Login from '../ui/Login/index.jsx';
import Head from 'next/head.js';

export default function LoginPage(){
    return ( 
        <div>
            <Head>
                <title>Meal Prep - Login</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
                <Navigation />
                <Login />
                <SiteMap />
        </div>
    )
}
